### ISSUE TITLE
Separate universe and view size settings

### ISSUE THREAD

**Issue by petrohi** [arnoldsz/game_of_life#1]
Please make possible to specify universe size separately from view size. For example I would like to have very large universe (1,000,000,000 x 1,000,000,000) while only render small view (50 x 50).

Please also add number of alive cells to status line.

**Comment by arnoldsz** [comment]
The display and universe size are already separated but only for universes larger than 100x100, I will make this configurable, and the default smaller.

Will also add the number of alive cells
